# Generated by Django 3.2.7 on 2021-10-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='super_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.tag'),
        ),
    ]
